name: Example Service Release

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["terraform/**"]

  pull_request:
    branches: [main]
    paths: ["terraform/**"]

jobs:
  plan:
    name: Terraform plan
    environment: dev
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Initialise project and view terraform plan
        run: |
          cd terraform 
          cd qa
          terraform fmt
          terraform init 
          terraform plan -var='example_api_key=${{ secrets.EXAMPLE_API_KEY }}'
      - name: Trigger deploy workflow
        uses: actions/github-script@v4
        with:
          script: |
            const { context, github } = require('@actions/github');
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy.yaml',
              ref: context.ref,
            });
